import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'testAngular';
  anhLuc = "Anh Lực 04 cũng chính là anh lực bất tử là anh của chúng sinh đứng đầu tam giới";
//Generated by typescript 1.8.10
   Person = (function () {
     return  "Hello Anh Minh Ngày 200.000$"
  }());
}





